### ISSUE TITLE
commandline skips all specs

### ISSUE THREAD

**Issue by wrzasa** [searls/jasmine-rails#226]
I'm trying to use `jasmine-rails` gem in my Rails app. It doesn't work in my Rails 4 legacy, so I tried minimal Rails 5 example and got the same problem.

I created new Rails 5 application, installed `jasmine-rails` gem, run `rails generate jasmine_rails:install`. Then I created `spec/javascripts/failure_spec.js` with the following content:

    describe('whatever, just give me failure!', function() {
      it('is skipped');
      it('fails', function() {
        expect(3).toBe(1);
        fail("designed failure")
      });

});

When I run `rake spec:javascript` it skips both specs:

    Running `"/home/wrzasa/.phantomjs/2.1.1/x86_64-linux/bin/phantomjs"  "/usr/local/rvm/gems/ruby-2.3.1@rails5/gems/jasmine-rails-0.14.6/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file:///tmp/js5/tmp/jasmine/runner.html?root=/tmp/js5&spec="`
    Running: file:///tmp/js5/tmp/jasmine/runner.html?root=/tmp/js5&spec=
    Starting...
    
    Finished
    -----------------
    2 specs, 2 skipped or pending, 0 failures in 0.027s.
    
    ConsoleReporter finished

But when I open http://localhost:3000/specs or open `tmp/jasmine/runner.html` in by browser it shows me `2 specs, 1 failure, 1 pending spec` with expected errors.

The minimal example reproducing the problem is [here on my github](https://github.com/wrzasa/jasmine-rails-not-working), feel free to use it if you want.

What's wrong with the `rake spec:javascripts` command? Where should I look for the reason for specs skipped by commandline?

I thought it's something basic, asked on [stackoverflow](https://stackoverflow.com/questions/46981445/jasmine-rails-gem-used-from-commandline-skips-all-my-specs-why), but got no answer so far. So... nobody knows?

**Comment by searls** [comment]
Can you try again with v0.14.3?

**Comment by wrzasa** [comment]
Well... yes, with 0.14.3 it works:

I get:

```
Finished
-----------------
2 specs, 1 skipped or pending, 1 failure in 0.03s.
```

...and the same result on www.

So it's not me! ;-) Something wrong with 0.14.6...

**Comment by searls** [comment]
I suspect @fmachella's PR that I merged in 2 days ago is the cause. Can you try manually reverting this (you can use `bundle show` or `bundle open` to edit the gem in place) and confirm that undoing this change fixes your issue?

https://github.com/searls/jasmine-rails/pull/216/files

**Comment by wrzasa** [comment]
Nope. I reverted the patch (you can notice changed URL in console output) and 0.14.6 still does not work:

```
wrzasa@ant /tmp/jasmine-rails-not-working $ bundle show jasmine-rails
/usr/local/rvm/gems/ruby-2.3.1@rails5/gems/jasmine-rails-0.14.6
wrzasa@ant /tmp/jasmine-rails-not-working $ bundle exec rake spec:javascripts
Running `"/home/wrzasa/.phantomjs/2.1.1/x86_64-linux/bin/phantomjs"  "/usr/local/rvm/gems/ruby-2.3.1@rails5/gems/jasmine-rails-0.14.6/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "file:///tmp/jasmine-rails-not-working/tmp/jasmine/runner.html?spec="`
Running: file:///tmp/jasmine-rails-not-working/tmp/jasmine/runner.html?spec=
Starting...

Finished
-----------------
2 specs, 2 skipped or pending, 0 failures in 0.028s.

ConsoleReporter finished
```

Incidentally, 0.14.7 works well.

**Comment by searls** [comment]
Oh, really? Well, then this fixed you: https://github.com/searls/jasmine-rails/pull/225

**Comment by wrzasa** [comment]
That's it ;-) Thank you!

And thanks for `bundle open` tip -- didn't know it, and it's a great tool! :D
